[xinfa]
xinfa_name = "mowen"
xinfa_nom = "根骨"
atk_up = 0.0
pofang_up = 0.0
huixin_up = 0.0

[player]
jcsx = "gengu"
jichu_shuxing = 100
jichu_gongji = 200
huixin_dengji = 1
huixin_xiaoguo = 10
pofang_dengji = 1
wuqi_shanghai = 50

[hostilepile]
waigong_fangyu = 100
neigong_fangyu = 100
yujin_dengji = 1
huajin_dengji = 1
jianshang_bili = 10
