[package]
name = "jpcg_update"
license.workspace = true
readme.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
indicatif = { workspace = true }
clap = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
toml = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
serde_json = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true
